[package]
name = "libcryptsetup-rs-sys"
version = "0.1.6"
authors = ["John Baublitz <jbaublitz@redhat.com>"]
edition = "2018"
description = "Low level bindings for libcryptsetup"
license = "MPL-2.0"
documentation = "https://docs.rs/libcryptsetup-rs-sys"
homepage = "https://stratis-storage.github.io/"
repository = "https://github.com/stratis-storage/libcryptsetup-rs"
categories = ["external-ffi-bindings"]

[build-dependencies]
bindgen = "0.59.0"
cc = "1.0.45"
pkg-config = "0.3.7"
semver = "1.0.0"
